### PR TITLE
FIX: Nakadi does not expect a token for PATCH /subscription/{id}/cursors

### PR DESCRIPTION
**Pull request by domizei385**

### CODE REVIEW

**Review by gchudnov — APPROVED** [review]

**Review by mdedetrich — APPROVED** [review]
Perfect thanks!

**Comment by gchudnov** [comment]
hm. but we can merge by `rebase & merge` option, right ?

**Comment by mdedetrich** [comment]
This doesn't work if you have merge conflicts. @domizei385 needs to update his fork's master at https://github.com/domizei385/kanadi to the latest version and then do the following

```
git checkout fixCursorPatch
git rebase origin/master
```

This will then go through the rebase process, once done you can just do `git push --force-with-lease`

**Comment by gchudnov** [comment]
@mdedetrich 
updated, please check

honestly a bit confused, I thought this conflict was already resolved before..

**Comment by mdedetrich** [comment]
All good from my end, also it seems like we don't need the thumbs up any more?

**Comment by gchudnov** [comment]
yes, it looks it is enough to approve it.

ok, I'm merging then..

**Pull request merged**
