### PR TITLE
set to 0.9.2-SNAPSHOT

### PR DESCRIPTION
**Pull request by gchudnov**

### CODE REVIEW

**Comment by mdedetrich** [comment]
Okay so for some reason DCO is not working because of the manual merging. Can you do a `git rebase origin/master` while checkout out in 0.9.x and then do `git push --force-with-lease` which should clean up all of these merge commits.

**Comment by gchudnov** [comment]
yes, messed up a bit,
now should be good

**Comment by gchudnov** [comment]
please bump

**Review by mdedetrich — APPROVED** [review]
Approved

**Comment by gchudnov** [comment]
thank you!

**Pull request merged**
