### PR TITLE
Migrate from Akka to Pekko

### PR DESCRIPTION
**Pull request by gchudnov**
### Description

overall tried to minimize the changes

- migration from akka to pekko 1.0.1 and pekko-http 1.0.0;
- updated dependencies;
- implemented workaround for https://github.com/mdedetrich/pekko-streams-circe/issues/15 (unmarshalAs);
- removed redundant dependencies.
- minor readme updates

NOTE: to minimize the amount of changes in the PR the support for Scala 3 is not included. Scala 3 support will be added right after this PR is merged and released.

### CODE REVIEW

**Comment by nejdaw** [comment]
I've run locally your changes and all tests are green. Thank you for this PR 🙂

**Comment by gchudnov** [comment]
@nejdaw 
if all good, please approve the PR so it can be merged (the invite should be sent to your email).

**Review by nejdaw — APPROVED** [review]
All tests pass locally

**Comment by gchudnov** [comment]
hm. when merged to master one test has failed, re-running.
Most likely unrelated to the current changes and caused by https://github.com/zalando-nakadi/kanadi/issues/176

**Comment by nejdaw** [comment]
Just updated to latest master and all of them passed.

**Pull request merged**
